use serde::Serialize;
use std::str::FromStr;

#[derive(Serialize, Debug)]
#[allow(non_camel_case_types, dead_code)]
pub enum RLMap {
    arc_darc_p,
    arc_p,
    arc_standard_p,
    bb_p,
    beach_night_p,
    beach_p,
    beachvolley,
    chn_stadium_day_p,
    chn_stadium_p,
    cs_day_p,
    cs_hw_p,
    cs_p,
    eurostadium_night_p,
    eurostadium_p,
    eurostadium_rainy_p,
    eurostadium_snownight_p,
    farm_hw_p,
    farm_night_p,
    farm_p,
    farm_upsidedown_p,
    ff_dusk_p,
    fni_stadium_p,
    haunted_trainstation_p,
    hoopsstadium_p,
    hoopsstreet_p,
    labs_circlepillars_p,
    labs_corridor_p,
    labs_cosmic_p,
    labs_cosmic_v4_p,
    labs_doublegoal_p,
    labs_doublegoal_v2_p,
    labs_octagon_02_p,
    labs_octagon_p,
    labs_pillarglass_p,
    labs_pillarwings_p,
    labs_underpass_p,
    labs_underpass_v0_p,
    labs_utopia_p,
    music_p,
    neotokyo_hax_p,
    neotokyo_p,
    neotokyo_standard_p,
    neotokyo_toon_p,
    outlaw_oasis_p,
    outlaw_p,
    park_bman_p,
    park_night_p,
    park_p,
    park_rainy_p,
    park_snowy_p,
    shattershot_p,
    stadium_day_p,
    stadium_foggy_p,
    stadium_p,
    stadium_race_day_p,
    stadium_winter_p,
    street_p,
    throwbackstadium_p,
    trainstation_dawn_p,
    trainstation_night_p,
    trainstation_p,
    underwater_p,
    utopiastadium_dusk_p,
    utopiastadium_lux_p,
    utopiastadium_p,
    utopiastadium_snow_p,
    wasteland_night_p,
    wasteland_night_s_p,
    wasteland_p,
    wasteland_s_p,
}

impl FromStr for RLMap {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "arc_darc_p" => Ok(RLMap::arc_darc_p),
            "arc_p" => Ok(RLMap::arc_p),
            "arc_standard_p" => Ok(RLMap::arc_standard_p),
            "bb_p" => Ok(RLMap::bb_p),
            "beach_night_p" => Ok(RLMap::beach_night_p),
            "beach_p" => Ok(RLMap::beach_p),
            "beachvolley" => Ok(RLMap::beachvolley),
            "chn_stadium_day_p" => Ok(RLMap::chn_stadium_day_p),
            "chn_stadium_p" => Ok(RLMap::chn_stadium_p),
            "cs_day_p" => Ok(RLMap::cs_day_p),
            "cs_hw_p" => Ok(RLMap::cs_hw_p),
            "cs_p" => Ok(RLMap::cs_p),
            "eurostadium_night_p" => Ok(RLMap::eurostadium_night_p),
            "eurostadium_p" => Ok(RLMap::eurostadium_p),
            "eurostadium_rainy_p" => Ok(RLMap::eurostadium_rainy_p),
            "eurostadium_snownight_p" => Ok(RLMap::eurostadium_snownight_p),
            "farm_hw_p" => Ok(RLMap::farm_hw_p),
            "farm_night_p" => Ok(RLMap::farm_night_p),
            "farm_p" => Ok(RLMap::farm_p),
            "farm_upsidedown_p" => Ok(RLMap::farm_upsidedown_p),
            "ff_dusk_p" => Ok(RLMap::ff_dusk_p),
            "fni_stadium_p" => Ok(RLMap::fni_stadium_p),
            "haunted_trainstation_p" => Ok(RLMap::haunted_trainstation_p),
            "hoopsstadium_p" => Ok(RLMap::hoopsstadium_p),
            "hoopsstreet_p" => Ok(RLMap::hoopsstreet_p),
            "labs_circlepillars_p" => Ok(RLMap::labs_circlepillars_p),
            "labs_corridor_p" => Ok(RLMap::labs_corridor_p),
            "labs_cosmic_p" => Ok(RLMap::labs_cosmic_p),
            "labs_cosmic_v4_p" => Ok(RLMap::labs_cosmic_v4_p),
            "labs_doublegoal_p" => Ok(RLMap::labs_doublegoal_p),
            "labs_doublegoal_v2_p" => Ok(RLMap::labs_doublegoal_v2_p),
            "labs_octagon_02_p" => Ok(RLMap::labs_octagon_02_p),
            "labs_octagon_p" => Ok(RLMap::labs_octagon_p),
            "labs_pillarglass_p" => Ok(RLMap::labs_pillarglass_p),
            "labs_pillarwings_p" => Ok(RLMap::labs_pillarwings_p),
            "labs_underpass_p" => Ok(RLMap::labs_underpass_p),
            "labs_underpass_v0_p" => Ok(RLMap::labs_underpass_v0_p),
            "labs_utopia_p" => Ok(RLMap::labs_utopia_p),
            "music_p" => Ok(RLMap::music_p),
            "neotokyo_hax_p" => Ok(RLMap::neotokyo_hax_p),
            "neotokyo_p" => Ok(RLMap::neotokyo_p),
            "neotokyo_standard_p" => Ok(RLMap::neotokyo_standard_p),
            "neotokyo_toon_p" => Ok(RLMap::neotokyo_toon_p),
            "outlaw_oasis_p" => Ok(RLMap::outlaw_oasis_p),
            "outlaw_p" => Ok(RLMap::outlaw_p),
            "park_bman_p" => Ok(RLMap::park_bman_p),
            "park_night_p" => Ok(RLMap::park_night_p),
            "park_p" => Ok(RLMap::park_p),
            "park_rainy_p" => Ok(RLMap::park_rainy_p),
            "park_snowy_p" => Ok(RLMap::park_snowy_p),
            "shattershot_p" => Ok(RLMap::shattershot_p),
            "stadium_day_p" => Ok(RLMap::stadium_day_p),
            "stadium_foggy_p" => Ok(RLMap::stadium_foggy_p),
            "stadium_p" => Ok(RLMap::stadium_p),
            "stadium_race_day_p" => Ok(RLMap::stadium_race_day_p),
            "stadium_winter_p" => Ok(RLMap::stadium_winter_p),
            "street_p" => Ok(RLMap::street_p),
            "throwbackstadium_p" => Ok(RLMap::throwbackstadium_p),
            "trainstation_dawn_p" => Ok(RLMap::trainstation_dawn_p),
            "trainstation_night_p" => Ok(RLMap::trainstation_night_p),
            "trainstation_p" => Ok(RLMap::trainstation_p),
            "underwater_p" => Ok(RLMap::underwater_p),
            "utopiastadium_dusk_p" => Ok(RLMap::utopiastadium_dusk_p),
            "utopiastadium_lux_p" => Ok(RLMap::utopiastadium_lux_p),
            "utopiastadium_p" => Ok(RLMap::utopiastadium_p),
            "utopiastadium_snow_p" => Ok(RLMap::utopiastadium_snow_p),
            "wasteland_night_p" => Ok(RLMap::wasteland_night_p),
            "wasteland_night_s_p" => Ok(RLMap::wasteland_night_s_p),
            "wasteland_p" => Ok(RLMap::wasteland_p),
            "wasteland_s_p" => Ok(RLMap::wasteland_s_p),
            _ => Err(()),
        }
    }
}

impl RLMap {
    pub fn as_ingame(&self) -> &'static str {
        match self {
            RLMap::arc_darc_p => "Starbase ARC (Aftermath)",
            RLMap::arc_p => "Starbase ARC",
            RLMap::arc_standard_p => "Starbase ARC (Standard)",
            RLMap::bb_p => "Champions Field (NFL)",
            RLMap::beach_night_p => "Salty Shores (Night)",
            RLMap::beach_p => "Salty Shores",
            RLMap::beachvolley => "Salty Shores (Volley)",
            RLMap::chn_stadium_day_p => "Forbidden Temple (Day)",
            RLMap::chn_stadium_p => "Forbidden Temple",
            RLMap::cs_day_p => "Champions Field (Day)",
            RLMap::cs_hw_p => "Rivals Arena",
            RLMap::cs_p => "Champions Field",
            RLMap::eurostadium_night_p => "Mannfield (Night)",
            RLMap::eurostadium_p => "Mannfield",
            RLMap::eurostadium_rainy_p => "Mannfield (Stormy)",
            RLMap::eurostadium_snownight_p => "Mannfield (Snowy)",
            RLMap::farm_hw_p => "Farmstead (Spooky)",
            RLMap::farm_night_p => "Farmstead (Night)",
            RLMap::farm_p => "Farmstead",
            RLMap::farm_upsidedown_p => "Farmstead (The Upside Down)",
            RLMap::ff_dusk_p => "Estadio Vida (Dusk)",
            RLMap::fni_stadium_p => "Forbidden Temple (Fire & Ice)",
            RLMap::haunted_trainstation_p => "Urban Central (Haunted)",
            RLMap::hoopsstadium_p => "Dunk House",
            RLMap::hoopsstreet_p => "The Block (Dusk)",
            RLMap::labs_circlepillars_p => "Pillars",
            RLMap::labs_corridor_p => "Corridor",
            RLMap::labs_cosmic_p => "Cosmic",
            RLMap::labs_cosmic_v4_p => "Cosmic",
            RLMap::labs_doublegoal_p => "Double Goal",
            RLMap::labs_doublegoal_v2_p => "Double Goal",
            RLMap::labs_octagon_02_p => "Octagon",
            RLMap::labs_octagon_p => "Octagon",
            RLMap::labs_pillarglass_p => "Hourglass",
            RLMap::labs_pillarwings_p => "Colossus",
            RLMap::labs_underpass_p => "Underpass",
            RLMap::labs_underpass_v0_p => "Underpass",
            RLMap::labs_utopia_p => "Utopia Retro",
            RLMap::music_p => "Neon Fields",
            RLMap::neotokyo_hax_p => "Neo Tokyo (Hacked)",
            RLMap::neotokyo_p => "Neo Tokyo",
            RLMap::neotokyo_standard_p => "Neo Tokyo (Standard)",
            RLMap::neotokyo_toon_p => "Neo Tokyo (Comic)",
            RLMap::outlaw_oasis_p => "Deadeye Canyon (Oasis)",
            RLMap::outlaw_p => "Deadeye Canyon",
            RLMap::park_bman_p => "Beckwith Park (Night)",
            RLMap::park_night_p => "Beckwith Park (Midnight)",
            RLMap::park_p => "Beckwith Park",
            RLMap::park_rainy_p => "Beckwith Park (Stormy)",
            RLMap::park_snowy_p => "Beckwith Park (Snowy)",
            RLMap::shattershot_p => "Core 707",
            RLMap::stadium_day_p => "DFH Stadium (Day)",
            RLMap::stadium_foggy_p => "DFH Stadium (Stormy)",
            RLMap::stadium_p => "DFH Stadium",
            RLMap::stadium_race_day_p => "DFH Stadium (Circuit)",
            RLMap::stadium_winter_p => "DFH Stadium (Snowy)",
            RLMap::street_p => "Sovereign Heights (Dusk)",
            RLMap::throwbackstadium_p => "Throwback Stadium",
            RLMap::trainstation_dawn_p => "Urban Central (Dawn)",
            RLMap::trainstation_night_p => "Urban Central (Night)",
            RLMap::trainstation_p => "Urban Central",
            RLMap::underwater_p => "Aquadome",
            RLMap::utopiastadium_dusk_p => "Utopia Coliseum (Dusk)",
            RLMap::utopiastadium_lux_p => "Utopia Coliseum (Gilded)",
            RLMap::utopiastadium_p => "Utopia Coliseum",
            RLMap::utopiastadium_snow_p => "Utopia Coliseum (Snowy)",
            RLMap::wasteland_night_p => "Wasteland (Night)",
            RLMap::wasteland_night_s_p => "Wasteland (Standard, Night)",
            RLMap::wasteland_p => "Wasteland",
            RLMap::wasteland_s_p => "Wasteland (Standard)",
        }
    }
}
